<!DOCTYPE html>
<html>
<head>
	<title>Error Handling using Finally </title>
</head>
<body>
	<!-- 
	In Javascript, for Error-handling to catch runtime errors, we can use try-catch-finally block of code.
	
	try: wrap suspicious code that may throw an error in try block.

	catch: write code to do something in catch block when an error occurs. The catch block can have parameters that will give you error information. Generally catch block is used to log an error or display specific messages to the user.

	finally: code in the finally block will always be executed regardless of the occurrence of an error. The finally block can be used to complete the remaining task or reset variables that might have changed before error occurred in try block.

	Basic Syntax for try-catch-finally will be:

	try
	{    // code that may throw an error }
	catch(ex)
	{  // code to be executed if an error occurs }
	finally 
	{   // code to be executed regardless of an error occurs or not }
-->
	<p>Using <b>try</b> , <b>catch</b> and <b>finally</b> to display an error.</p>
	<p id="para"></p>
	<p id="para1"></p>

	<script>
		try {
			//alert("Welcome guest!");
		  adddert("Welcome guest!"); //error in this line
		}
		catch(err) {
		  document.getElementById("para").innerHTML = err.message; // inspite of error, below code inside catch will be executed.
		  alert(`Welcome guest inside the catch function`);

		}
		finally{
			alert(`Welcome u are inside the finally block`);
			document.getElementById("para1").innerHTML = "finally block executed";
			document.write(`It should be  "alert" instead of "adddert"`)
		}

	</script>
</body>
</html>
